services:
    database:
        image: "postgres:latest"
        ports:
            - "${DATABASE_PORT}:5432"
        environment:
            - "POSTGRES_USER=${DATABASE_USER}"
            - "POSTGRES_PASSWORD=${DATABASE_PASSWORD}"
            - "POSTGRES_DB=${DATABASE_DATABASE}"
        restart: unless-stopped
    countula:
        image: zaptross/countula:latest
        depends_on:
            - database
        environment:
            - "DISCORD_TOKEN=${DISCORD_TOKEN}"
            - "DISCORD_APPID=${DISCORD_APPID}"
            - "DATABASE_USER=${DATABASE_USER}"
            - "DATABASE_PASSWORD=${DATABASE_PASSWORD}"
            - "DATABASE_DATABASE=${DATABASE_DATABASE}"
            - "DATABASE_PORT=${DATABASE_PORT}"
            - "DATABASE_HOST=database"
            - "DATABASE_SSL=${DATABASE_SSL}"
            - "DATABASE_TIMEZONE=${DATABASE_TIMEZONE}"
