version: "3.9"
services:
  postgres:
    image: "${TYPEORM_DATABASE_ENGINE}:${TYPEORM_DATABASE_VERSION}"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=${TYPEORM_USERNAME}"
      - "POSTGRES_PASSWORD=${TYPEORM_PASSWORD}"
      - "POSTGRES_DB=${TYPEORM_DATABASE}"
