apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "countula.fullname" .}}
data:
  {{- range $key, $val := .Values.countula.discord }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- range $key, $val := .Values.countula.database }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}