name: Container Build

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - "*"
      - "**"
      - "*/*"

jobs:
  build:
    environment: Image Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
